### ISSUE TITLE
Order page not showing

### ISSUE THREAD

**Issue by tej-1441** [CleverProgrammers/react-challenge-amazon-clone#34]
When payment is submitted then it redirect to order page but my ordered item are not showing.pls help

**Comment by tej-1441** [comment]
It

**Comment by SebastianDevelops** [comment]
Check your react-router-dom version. Check to see if it's the same as the version in the tutorial.

In react-router-Dom V6 we don't use <Switch> anymore and they used <Switch> in the tutorial.

Instead we replace <Switch> with <Routes> and also all your components need to be called in JSX

Eg.
<Route path="/"> element={<Home/>}  />

Instead of
<Route path="/"> 
    <Home />
  </Route>

If you want to avoid changing all of that just run npm install react-router-dom@5.2.0

That will downgrade the version.

I apologize for the sloppiness I typed this out on my phone lol.
